HSDK v3.0 Benchmarking (#744)
* Bump holoscan-networking to 0.1

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* HSDK v3.0 Benchmarking

Signed-off-by: vani-nag <vanihannah@gmail.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Update Contribution Guide and Docs for Workflows (#742)

* Add workflows readme
* update CONTRIBUTING.md for developing workflows

---------

Signed-off-by: B Hashemian <3968947+bhashemian@users.noreply.github.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* removed pdf parts

Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* removed pdf part

Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* fixed image links

Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* HSDK v3.0 Benchmark Report

Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Fixes for `yolo_model_deployment` build (#740)

Addresses observed issues:
- Build failure due to both BYPRODUCTS and OUTPUT generating data files,
  possibly observed now with switch to Ninja build system in a734ed58a.
  Resolves error message:
```
ninja: error: build.ninja:1440: multiple rules generate /workspace/holohub/data/yolo_model_deployment/meeting.gxf_index [-w dupbuild=err]
```

- Persist YOLOv8-TensorRT repo to avoid error where ONNX generation
  failure could leave the build folder in a bad state with fail on the
  next `git clone YOLOv8-TensorRT`

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Rename platform names in metadata (#747)

arm64 -> aarch64
amd64 -> x86_64

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Fixes for `vila_live` build (#746)

* Fixes for `vila_live` build

Updates to fix `vila_live` build errors following HoloHub default
generator update to Ninja.

Addresses errors on x86 platform:

Docker build:
```bash
0.454 Collecting flash-attn~=2.5
0.694   Downloading flash_attn-2.7.4.post1.tar.gz (6.0 MB)
1.893      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 5.3 MB/s eta 0:00:00
2.687   Preparing metadata (setup.py): started
2.746   Preparing metadata (setup.py): finished with status 'error'
2.748   error: subprocess-exited-with-error
2.748
2.748   × python setup.py egg_info did not run successfully.
2.748   │ exit code: 1
2.748   ╰─> [6 lines of output]
2.748       Traceback (most recent call last):
2.748         File "<string>", line 2, in <module>
2.748         File "<pip-setuptools-caller>", line 34, in <module>
2.748         File "/tmp/pip-install-yjwnc8sl/flash-attn_42b07c7ef9e64ab497235f9174b57d88/setup.py", line 12, in <module>
2.748           from packaging.version import parse, Version
2.748       ModuleNotFoundError: No module named 'packaging'
```

CMake build:
```sh
[command] cmake --build build/vila_live -j
ninja: error: build.ninja:1440: multiple rules generate /workspace/holohub/data/vila_live/meeting.gxf_index
```

A runtime error is observed and requires further investigation:
```sh
ImportError: cannot import name 'is_torch_greater_or_equal_than_1_13' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)
```

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>

* Revert "Bump transformers (#734)"

This reverts commit 0cd5a30a6379314f684be49df462f2c56b4dbade.

Addresses issue after upgrade:
```
ImportError: cannot import name 'is_torch_greater_or_equal_than_1_13' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)
```

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>

---------

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Remove COMING SOON ano debian install

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* ANO tutorial: secure boot disabling

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Show sample app config post-placeholder

Users were confused about the `< >` and left them.

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* ano tutorial: improve sfp cable references

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* ano tutorial: document container run

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* ano tutorial: bump to rank 1

SQA and mini-vdr passed

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* fixes llm init

Signed-off-by: Wenqi Li <wenqil@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* using an updated version of the awq model

Signed-off-by: Wenqi Li <wenqil@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Update comment

Signed-off-by: Wenqi Li <831580+wyli@users.noreply.github.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Update README.md

Signed-off-by: Wenqi Li <831580+wyli@users.noreply.github.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Fix run:get_app_dockerfile

Do not ignore language parameter

Regression introduced in #712

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Update platform names in CONTRIBUTING

Align with #747

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Call adequate lint tools through python driver

ruff, isort and black are installed as pip packages, and can run with
`python3 -m <tool>`

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

* Update applications/vila_live/README.md

Co-authored-by: Tom Birdsong <40648863+tbirdso@users.noreply.github.com>
Signed-off-by: Wenqi Li <831580+wyli@users.noreply.github.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>

---------

Signed-off-by: Alexis Girault <agirault@nvidia.com>
Signed-off-by: Vani Nagarajan <vanin@nvidia.com>
Signed-off-by: vani-nag <vanihannah@gmail.com>
Signed-off-by: B Hashemian <3968947+bhashemian@users.noreply.github.com>
Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>
Signed-off-by: Wenqi Li <wenqil@nvidia.com>
Signed-off-by: Wenqi Li <831580+wyli@users.noreply.github.com>
Co-authored-by: Alexis Girault <agirault@nvidia.com>
Co-authored-by: Bruce Hashemian <3968947+bhashemian@users.noreply.github.com>
Co-authored-by: Tom Birdsong <40648863+tbirdso@users.noreply.github.com>
Co-authored-by: Alexis Girault <agirault@users.noreply.github.com>
Co-authored-by: Wenqi Li <wenqil@nvidia.com>
Co-authored-by: Wenqi Li <831580+wyli@users.noreply.github.com>